// Markdown içindeki "Proje Dosyaları" bölümünü ayrıştırır ve Next.js ZIP paketi oluşturur.
// Service worker'da importScripts ile kullanılabilmek için global olarak tanımlanır.

const SCAFFOLD_SECTION_HEADER = "## Proje Dosyaları (Scaffold)";
const FILE_PATH_PATTERN = /^###\s*FILE:\s*(.+)$/i;

const DEFAULT_SCAFFOLD_FILES = {
  "package.json": JSON.stringify(
    {
      name: "rebuilt-site",
      version: "0.1.0",
      private: true,
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
        lint: "next lint",
      },
      dependencies: {
        next: "^15.0.0",
        react: "^19.0.0",
        "react-dom": "^19.0.0",
        "class-variance-authority": "^0.7.0",
        clsx: "^2.1.0",
        "tailwind-merge": "^2.5.0",
        "lucide-react": "^0.460.0",
      },
      devDependencies: {
        typescript: "^5.6.0",
        "@types/node": "^22.0.0",
        "@types/react": "^19.0.0",
        tailwindcss: "^3.4.0",
        postcss: "^8.4.0",
        autoprefixer: "^10.4.0",
      },
    },
    null,
    2
  ),
  "next.config.ts": `import type { NextConfig } from "next";

const nextConfig: NextConfig = {};

export default nextConfig;
`,
  "tsconfig.json": JSON.stringify(
    {
      compilerOptions: {
        target: "ES2017",
        lib: ["dom", "dom.iterable", "esnext"],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "preserve",
        incremental: true,
        plugins: [{ name: "next" }],
        paths: { "@/*": ["./src/*"] },
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
      exclude: ["node_modules"],
    },
    null,
    2
  ),
  "tailwind.config.ts": `import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{ts,tsx}"],
  theme: { extend: {} },
  plugins: [],
};

export default config;
`,
  "postcss.config.mjs": `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
`,
  "src/app/globals.css": `@tailwind base;
@tailwind components;
@tailwind utilities;
`,
  "README.md": `# Rebuilt Site

Generated by MD Page Analysis extension.

\`\`\`bash
npm install
npm run dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000).
`,
};

function parseScaffoldFiles(markdown) {
  const files = { ...DEFAULT_SCAFFOLD_FILES };
  const sectionIndex = markdown.indexOf(SCAFFOLD_SECTION_HEADER);
  if (sectionIndex === -1) return files;

  const scaffoldBody = markdown.slice(sectionIndex + SCAFFOLD_SECTION_HEADER.length);
  const lines = scaffoldBody.split("\n");
  let currentPath = null;
  let fenceBuffer = [];
  let insideFence = false;

  const flushFence = () => {
    if (!currentPath || fenceBuffer.length === 0) return;
    const normalized = currentPath.trim().replace(/^\/+/, "");
    if (normalized && !normalized.includes("..")) {
      files[normalized] = fenceBuffer.join("\n").trimEnd();
    }
    fenceBuffer = [];
    insideFence = false;
  };

  for (const line of lines) {
    const pathMatch = line.match(FILE_PATH_PATTERN);
    if (pathMatch) {
      flushFence();
      currentPath = pathMatch[1];
      continue;
    }

    if (line.startsWith("```")) {
      if (insideFence) {
        flushFence();
      } else {
        insideFence = true;
        fenceBuffer = [];
      }
      continue;
    }

    if (insideFence) {
      fenceBuffer.push(line);
    }

    if (line.startsWith("## ") && !line.startsWith(SCAFFOLD_SECTION_HEADER)) {
      break;
    }
  }

  flushFence();
  return files;
}

async function buildProjectZip(markdown, projectName) {
  const files = parseScaffoldFiles(markdown);
  const zip = new JSZip();

  for (const [filePath, content] of Object.entries(files)) {
    zip.file(filePath, content);
  }

  const blob = await zip.generateAsync({ type: "blob" });
  return { blob, fileCount: Object.keys(files).length };
}

async function blobToDataUrl(blob) {
  const buffer = await blob.arrayBuffer();
  const bytes = new Uint8Array(buffer);
  let binary = "";
  for (let i = 0; i < bytes.length; i++) {
    binary += String.fromCharCode(bytes[i]);
  }
  return `data:application/zip;base64,${btoa(binary)}`;
}
